### ISSUE TITLE
Convert raw SQL to ORM

### ISSUE THREAD

**Issue by raphattack** [raphattack/espn-ffb#1]
The following queries need to be converted to the ORM equivalent:

- [get_h2h_records](https://github.com/raphattack/espn-ffb/blob/master/espn_ffb/db/query.py#L66-L115)
- [get_standings](https://github.com/raphattack/espn-ffb/blob/master/espn_ffb/db/query.py#L169-L208)
- [get_standings_overall](https://github.com/raphattack/espn-ffb/blob/master/espn_ffb/db/query.py#L219-L251)

**Comment by shaibruhis** [comment]
Do you have an ORM already being used for other queries? If not do you have a preference on which ORM is used?

**Comment by raphattack** [comment]
SQLAlchemy is already being used. These three queries are the only ones remaining that needs to be converted.

**Comment by smfarrelly** [comment]
FYI If you're looking to support non postgres dbs I think the insert will need to be refactored to not rely on the postgresql dialect as well.

https://github.com/raphattack/espn-ffb/blob/master/espn_ffb/db/query.py#L9

**Comment by smfarrelly** [comment]
get_h2h_standings could _probably_ be left as raw sql as I don't see anything there that's database specific. For the others the `::` Cast operator is postgres specific I believe, but that could be updated to CAST() which should work more broadly.

**Comment by raphattack** [comment]
Really appreciate the help @smfarrelly!
