### ISSUE TITLE
Merge Owners where member changed their email

### ISSUE THREAD

**Issue by amcorral** [raphattack/espn-ffb#4]
I noticed that two of my league's members changed their emails at some point in our league's long history. I'm wondering if there is a way to merge an owner record if first names match or something? Any insight here would be super helpful. Thanks.

**Comment by amcorral** [comment]
This is a screenshot of where I think the issue stems from. 

<img width="485" alt="Screen Shot 2020-07-19 at 2 51 54 PM" src="https://user-images.githubusercontent.com/22014463/87886153-87ae9400-c9cf-11ea-806b-775521ecb24b.png">

<img width="519" alt="Screen Shot 2020-07-19 at 2 51 43 PM" src="https://user-images.githubusercontent.com/22014463/87886155-88dfc100-c9cf-11ea-924b-a2ed0db8a899.png">

[](url)

**Comment by raphattack** [comment]
Not sure if you are using Docker, but assuming you are, I just pushed [this commit](https://github.com/raphattack/espn-ffb/commit/940a3456e3a19ace4b20faf133f5dde642a76a3c) to expose port 5432.

Matching first names will not work for everyone, so it is better to resolve this redundancy by updating the data within your own database.

Easiest way to do this is to connect to Postgres with an IDE. I use [DBeaver](https://dbeaver.io/download/).

Once connected, you can run the following statements:
```sql
update champions
set owner_id = 'new_owner_id'
where owner_id = 'old_owner_id';

update matchups
set owner_id = 'new_owner_id'
where owner_id = 'old_owner_id';

update matchups
set opponent_owner_id = 'new_owner_id'
where opponent_owner_id = 'old_owner_id';

update records
set owner_id = 'new_owner_id'
where owner_id = 'old_owner_id';

update sackos
set owner_id = 'new_owner_id'
where owner_id = 'old_owner_id';

update teams
set owner_id = 'new_owner_id'
where owner_id = 'old_owner_id';

delete from owners
where owner_id = 'old_owner_id';
```

**Comment by amcorral** [comment]
Awesome! This was super helpful. All the duplicate owners were merged and then deleted. I really like the visual database as well. Thanks so much for the help.
